AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Infraestructura base para desplegar el backend de la prueba técnica BTG Pactual
  en una instancia EC2 usando Docker.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nombre del KeyPair para conectarse por SSH

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
    Description: Tipo de instancia EC2

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: Amazon Linux 2023 más reciente

Resources:
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para backend BTG Funds API
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  BackendInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: btg-funds-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  BackendInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BackendInstanceRole

  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref BackendInstanceProfile
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      Tags:
        - Key: Name
          Value: btg-funds-api-ec2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y docker git
          systemctl enable docker
          systemctl start docker
          usermod -aG docker ec2-user

Outputs:
  InstanceId:
    Description: ID de la instancia EC2
    Value: !Ref BackendInstance

  PublicIp:
    Description: IP pública de la instancia
    Value: !GetAtt BackendInstance.PublicIp

  PublicDns:
    Description: DNS público de la instancia
    Value: !GetAtt BackendInstance.PublicDnsName